server:
  port: 8761

spring:
  application:
    name: starline-service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false
